//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PtclCustomerService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PTCLEntities : DbContext
    {
        public PTCLEntities()
            : base("name=PTCLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblPtclUser> tblPtclUsers { get; set; }
        public virtual DbSet<tblAdmin> tblAdmins { get; set; }
    
        public virtual ObjectResult<PtclUserLogin_Result> PtclUserLogin(string email, string password)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PtclUserLogin_Result>("PtclUserLogin", emailParameter, passwordParameter);
        }
    
        public virtual ObjectResult<PtclAdminLogin_Result> PtclAdminLogin(string userName, string password)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PtclAdminLogin_Result>("PtclAdminLogin", userNameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<GetPtclUsers_Result> GetPtclUsers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPtclUsers_Result>("GetPtclUsers");
        }
    
        public virtual int DeletePtlcUser(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeletePtlcUser", userIDParameter);
        }
    
        public virtual ObjectResult<GetPtclAdmins_Result> GetPtclAdmins()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPtclAdmins_Result>("GetPtclAdmins");
        }
    
        public virtual int DeletePtclAdmin(Nullable<int> adminID)
        {
            var adminIDParameter = adminID.HasValue ?
                new ObjectParameter("AdminID", adminID) :
                new ObjectParameter("AdminID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeletePtclAdmin", adminIDParameter);
        }
    }
}
