//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PtclCustomerService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserLocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUserLocation()
        {
            this.tblPtclUsers = new HashSet<tblPtclUser>();
        }
    
        public int LocationID { get; set; }
        public Nullable<int> LocationCode { get; set; }
        public string LocationName { get; set; }
        public string Locationprovince { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPtclUser> tblPtclUsers { get; set; }
    }
}
